CREATE TABLE IF NOT EXISTS SECTORS (
    SECTOR_ID BIGSERIAL NOT NULL PRIMARY KEY,
    SECTOR_VALUE VARCHAR(255) NOT NULL CHECK(UPPER(SECTOR_VALUE) = SECTOR_VALUE),
    SECTOR_DESCRIPTION VARCHAR(255),
    SECTOR_PARENT_VALUE VARCHAR(255) NOT NULL CHECK(UPPER(SECTOR_PARENT_VALUE) = SECTOR_PARENT_VALUE),
    SECTOR_ORDER INTEGER NOT NULL,
    UNIQUE(SECTOR_VALUE)
);

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID BIGSERIAL NOT NULL PRIMARY KEY,
    USER_FIRST_NAME VARCHAR(255) NOT NULL,
    USER_SESSION_ID VARCHAR(255) NOT NULL,
    UNIQUE(USER_SESSION_ID)
);

CREATE TABLE IF NOT EXISTS USER_SECTORS(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    SECTOR_ID BIGINT NOT NULL,
    CONSTRAINT FK_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_SECTOR FOREIGN KEY(SECTOR_ID) REFERENCES SECTORS(SECTOR_ID)
);