INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('MANUFACTURING', 'Manufacturing', 'MANUFACTURING', 1);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('CONSTRUCTION_MATERIALS', 'Construction materials', 'MANUFACTURING', 2);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('ELECTRONICS_AND_OPTICS', 'Electronics and Optics', 'MANUFACTURING', 3);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('FOOD_BEVERAGE', 'Food and Beverage', 'MANUFACTURING', 4);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('BAKERY', 'Bakery &amp; confectionery products', 'FOOD_BEVERAGE', 5);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('BEVERAGES', 'Beverages', 'FOOD_BEVERAGE',6 );
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('FISH_PRODUCTS', 'Fish &amp; fish products', 'FOOD_BEVERAGE', 7);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('MEAT_PRODUCTS', 'Meat &amp; meat products', 'FOOD_BEVERAGE', 8);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('MILK_PRODUCTS', 'Milk &amp; dairy products', 'FOOD_BEVERAGE', 9);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('OTHER', 'Other', 'FOOD_BEVERAGE', 10);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('SWEET_FOOD', 'Sweets &amp; snack food', 'FOOD_BEVERAGE',11 );
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('FURNITURE', 'Furniture', 'MANUFACTURING', 12);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('BATHROOM', 'Bathroom/sauna', 'FURNITURE', 13);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('BEDROOM', 'Bedroom', 'FURNITURE', 14);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('CHILDREN', 'Children’s room', 'FURNITURE', 15);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('KITCHEN', 'Kitchen', 'FURNITURE', 16);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('LIVING', 'Living room', 'FURNITURE', 17);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('OFFICE', 'Office', 'FURNITURE',18);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('OTHER_FURNITURE', 'Other (Furniture)', 'FURNITURE', 19);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('OUTDOOR', 'Outdoor', 'FURNITURE', 20);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('PROJECT_FURNITURE', 'Project furniture', 'FURNITURE', 21);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('MACHINERY', 'Machinery', 'MANUFACTURING', 22);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('MACHINERY_COMPONENTS', 'Machinery components', 'MACHINERY',23 );
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('MACHINERY_TOOLS', 'Machinery equipment/tools', 'MACHINERY', 24);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('MANUFACTURE_MACHINERY', 'Manufacture of machinery', 'MACHINERY', 25);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('MARITIME', 'Maritime', 'MACHINERY', 26);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('ALUMINUM', 'Aluminium and steel workboats', 'MARITIME', 27);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('BOAT', 'Boat/Yacht building', 'MARITIME', 28);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('SHIP', 'Ship repair and conversion', 'MARITIME', 29);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('METAL_STRUCTURES', 'Metal structures', 'MACHINERY', 30);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('OTHER_SOME', 'Other', 'MACHINERY', 31);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('REPAIR', 'Repair and maintenance service', 'MACHINERY',32 );
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('METALWORKING', 'Metalworking', 'MANUFACTURING', 33);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('CONSTRUCTION', 'Construction of metal structures', 'MANUFACTURING', 34);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('HOUSES_BUILDINGS', 'Houses and buildings', 'MANUFACTURING', 35);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('METAL', 'Metal products', 'MANUFACTURING', 36);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('METAL_WORKS', 'Metal works', 'MANUFACTURING', 37);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('CNC', 'CNC-machining', 'METAL_WORKS', 38);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('FASTENERS', 'Forgings, Fasteners', 'METAL_WORKS', 39);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('GAS', 'Gas, Plasma, Laser cutting', 'METAL_WORKS', 40);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('MIG', 'MIG, TIG, Aluminum welding', 'METAL_WORKS', 41);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('PLASTIC_AND_RUBBER', 'Plastic and Rubber', 'MANUFACTURING', 42);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('PACKAGING', 'Packaging', 'PLASTIC_AND_RUBBER', 43);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('PLASTIC', 'Plastic goods', 'PLASTIC_AND_RUBBER', 44);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('PLASTIC_TECH', 'Plastic processing technology', 'PLASTIC_AND_RUBBER', 45);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('BLOWING', 'Blowing', 'PLASTIC_TECH', 46);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('MOULDING', 'Moulding', 'PLASTIC_TECH', 47);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('WELDING', 'Plastics welding and processing', 'PLASTIC_TECH',48 );
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('PLASTIC_PROFILES', 'Plastic profiles', 'PLASTIC_AND_RUBBER', 49);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('PRINTING', 'Printing', 'MANUFACTURING', 50);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('ADVERTISING', 'Advertising', 'PRINTING', 51);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('BOOK', 'Book/Periodicals printing', 'PRINTING', 52);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('LABELLING', 'Labelling and packaging printing', 'PRINTING', 53);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('TEXTILE_CLOTHING', 'Textile and Clothing', 'MANUFACTURING', 54);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('CLOTHING', 'Clothing', 'TEXTILE_CLOTHING', 55);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('TEXTILE', 'Textile', 'TEXTILE_CLOTHING', 56);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('WOOD', 'Wood', 'MANUFACTURING', 57);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('OTHER_WOOD', 'Other (Wood)', 'WOOD', 58);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('WOODEN_BUILDING', 'Wooden building materials', 'WOOD', 59);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('HOUSES', 'Wooden houses', 'WOOD', 60);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('OTHER_GLOBAL', 'Other', 'OTHER_GLOBAL', 61);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('CREATIVE', 'Creative industries', 'OTHER_GLOBAL', 62);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('ENERGY', 'Energy technology', 'OTHER_GLOBAL', 63);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('ENVIRONMENT', 'Environment', 'OTHER_GLOBAL', 64);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('SERVICE', 'Service', 'SERVICE',65 );
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('BUSINESS', 'Business services', 'SERVICE', 66);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('ENGINEERING', 'Engineering', 'SERVICE', 67);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('INFO_TEL', 'Information Technology and Telecommunications', 'SERVICE', 68);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('DATA_PROC', 'Data processing, Web portals, E-marketing', 'INFO_TEL', 69);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('PROGRAMMING', 'Programming, Consultancy', 'INFO_TEL', 70);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('SOFTWARE', 'Software, Hardware', 'INFO_TEL', 71);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('TEL', 'Telecommunications', 'INFO_TEL', 72);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('TOURISM', 'Tourism', 'SERVICE', 73);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('TRANSLATION', 'Translation services', 'SERVICE', 74);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('TRANSPORT', 'Transport and Logistics', 'SERVICE',75 );
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('AIR', 'Air', 'TRANSPORT', 76);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('RAIL', 'Rail', 'TRANSPORT', 77);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('ROAD', 'Road', 'TRANSPORT', 78);
INSERT INTO SECTORS (SECTOR_VALUE, SECTOR_DESCRIPTION, SECTOR_PARENT_VALUE, SECTOR_ORDER)
VALUES ('WATER', 'Water', 'TRANSPORT', 79);